### ISSUE TITLE
Super Video asking logged in users and admins to login to watch specific videos

### ISSUE THREAD

**Issue by jimmyjimbo22** [EduardoKrausME/moodle-mod_supervideo#30]
I have a site with more than 35 courses, on specific courses and specific videos, the video cannot be played and triggers the login screen a lot of times. It never plays after logging in, it prompts the login again.

**Comment by jimmyjimbo22** [comment]
![WhatsApp Image 2024-08-23 at 15 59 42_2003151b](https://github.com/user-attachments/assets/025ccdc7-887c-4fd1-abce-03fc73f0e1ef)

The issue happens on phones generally and the Moodle App

**Comment by eduardokraus** [comment]
Hi,

Thank you for bringing this issue to our attention. I sent an update a few months ago that includes the fix for this video playback problem. I recommend checking if the update has been applied correctly. If the issue persists, please let me know so we can investigate further.

I'm here to help!

Best regards,
Eduardo Kraus
